"""Generate the knife variants of the PiPER scene.

The existing scene files (piper.xml, piper_task.xml, piper_human_task.xml) are
left untouched so every earlier result stays reproducible. MJCF cannot add a
child body to a body that lives in an included file, so the knife variants are
generated copies:

    agilex_piper/piper_knife.xml             piper.xml + knife welded to link6
    agilex_piper/piper_human_knife_task.xml  piper_task.xml (with piper_knife.xml)
                                             + the human bodies of piper_human_task.xml

Run `python -m piper_rl.scripts.make_knife_scene` after changing any of the
three source files. tests/test_knife_scene.py fails if the generated files drift.

Knife mounting: the handle centre sits on the `tcp` site and the blade runs
along the gripper approach axis (link6 +z), edge toward link6 -x. Knife geoms
have contype=conaffinity=0, so the knife does not change contacts or the
existing robot/human collision logic; the hazard wrapper measures it
geometrically. The knife body carries gravcomp=1 like every arm link.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCENE_DIR = ROOT / "agilex_piper"

KNIFE_ASSETS = """
    <!-- knife (generated by piper_rl/scripts/make_knife_scene.py) -->
    <material name="knife_steel" rgba="0.75 0.77 0.80 1" specular="0.9" shininess="0.8"/>
    <material name="knife_handle" rgba="0.12 0.08 0.05 1"/>
"""

# Knife frame: +X handle->tip, +Z out of the edge. quat = rotation about y by -90 deg,
# so knife +X -> link6 +z. pos puts the handle centre (knife x = -0.055) on tcp (z = 0.105).
KNIFE_BODY = """
                  <!-- Knife held in the gripper. Sites: blade_heel, blade_tip (edge ends),
                       blade_frame (local +z = cutting direction). Non-colliding by design. -->
                  <body name="knife" pos="0 0 0.16" quat="0.70710678 0 -0.70710678 0" gravcomp="1">
                    <geom name="knife_handle" type="box" size="0.055 0.011 0.013" pos="-0.055 0 0"
                          material="knife_handle" mass="0.08" contype="0" conaffinity="0" group="2"/>
                    <geom name="knife_blade" type="box" size="0.100 0.001 0.020" pos="0.100 0 0"
                          material="knife_steel" mass="0.08" contype="0" conaffinity="0" group="2"/>
                    <site name="blade_heel" pos="0.000 0 0.020" size="0.003" rgba="1 0 0 1"/>
                    <site name="blade_tip" pos="0.200 0 0.020" size="0.003" rgba="1 0 0 1"/>
                    <site name="blade_frame" pos="0.100 0 0.020" size="0.002" rgba="0 1 0 0.5"/>
                  </body>
"""


def build_piper_knife(src: str) -> str:
    out = src.replace('<mujoco model="piper_description">', '<mujoco model="piper_description_knife">', 1)
    out = out.replace("<asset>", "<asset>" + KNIFE_ASSETS, 1)
    marker = '                  <body name="link7"'
    assert out.count(marker) == 1, "link7 marker not found exactly once in piper.xml"
    return out.replace(marker, KNIFE_BODY.lstrip("\n") + marker, 1)


def build_human_knife_task(task_src: str, human_src: str) -> str:
    out = task_src.replace('<mujoco model="piper_pick_place">',
                           '<mujoco model="piper_human_aware_pick_place_knife">', 1)
    assert '<include file="piper.xml"/>' in out
    out = out.replace('<include file="piper.xml"/>', '<include file="piper_knife.xml"/>', 1)
    material = re.search(r"<asset>\s*(<material name=\"human_skin\"[^>]*/>)\s*</asset>", human_src)
    bodies = re.search(r"<worldbody>(.*)</worldbody>", human_src, re.S)
    assert material and bodies, "unexpected piper_human_task.xml layout"
    out = out.replace("  <worldbody>", "  <asset>\n    " + material.group(1) + "\n  </asset>\n\n  <worldbody>", 1)
    out = out.replace("  </worldbody>", "\n    <!-- ===== human arm (from piper_human_task.xml) ===== -->"
                      + bodies.group(1).rstrip() + "\n  </worldbody>", 1)
    return out


def generate() -> dict[str, str]:
    piper = (SCENE_DIR / "piper.xml").read_text()
    task = (SCENE_DIR / "piper_task.xml").read_text()
    human = (SCENE_DIR / "piper_human_task.xml").read_text()
    return {
        "piper_knife.xml": build_piper_knife(piper),
        "piper_human_knife_task.xml": build_human_knife_task(task, human),
    }


def main() -> None:
    for name, text in generate().items():
        (SCENE_DIR / name).write_text(text)
        print("wrote", SCENE_DIR / name)


if __name__ == "__main__":
    main()
